import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import { generateId, initializeDatabase } from '../db/database';
import {
  getInventoryItem,
  loadActiveInventory,
  loadCompletedSales,
  markInventorySold,
  sanitizeImageUrl,
  softDeleteInventoryItem,
  unmarkInventorySold,
  upsertInventoryItem,
  type PersistedCompletedSale,
  type PersistedInventory,
} from '../db/inventoryDb';
import {
  getCatalogImageBase64,
  getProductMarketData,
  openCatalogDatabase,
  type ProductMarketMap,
} from '../db/catalogDb';
import {
  pullCloudInventory,
  pushPendingInventoryChanges,
  SyncFatalError,
} from '../api/cloudSync';
import { clearPendingSyncs, getPendingInventoryCount } from '../db/syncDb';
import { INVENTORY_IMAGE_BASE } from '../constants/api';
import { useAuth } from './AuthContext';
import { useVendorSettings } from './VendorSettingsContext';

export type InventoryCard = {
  id: string;
  name: string;
  number?: string;
  set?: string;
  rarity?: string;
  productType?: string;
  condition?: string;
  liveMarket: number;
  amountPaid: number;
  stickerPrice: number;
  projProfit: number;
  stock: number;
  isBulk?: boolean;
  imageUrl?: string;
  productId?: number | null;
};

export type InventoryInput = {
  id?: string;
  name: string;
  number?: string;
  set?: string;
  rarity?: string;
  productType?: string;
  condition?: string;
  liveMarket: number;
  amountPaid?: number;
  stickerPrice?: number;
  isBulkDeal?: boolean;
  imageUrl?: string;
  productId?: number | null;
};

export type InventoryUpdate = {
  id: string;
} & Partial<InventoryInput>;

export type CompletedSale = {
  id: string;
  name: string;
  number?: string;
  set?: string;
  condition?: string;
  acquiredCost: number;
  soldPrice: number;
  dateSold: string;
};

type InventoryContextValue = {
  inventory: InventoryCard[];
  addInventoryCard: (card: InventoryInput) => void;
  removeInventoryCard: (id: string) => void;
  updateInventoryCard: (updates: InventoryUpdate) => void;
  sellInventoryCard: (id: string, soldPrice?: number) => void;
  clearInventory: () => void;
  completedSales: CompletedSale[];
  undoCompletedSale: (sale: CompletedSale) => void;
  pendingSyncCount: number;
  isSyncing: boolean;
  syncFatalError: string | null;
  triggerSync: () => Promise<void>;
  clearPendingSyncs: () => Promise<void>;
  forceWipeAndResync: () => Promise<void>;
};

const InventoryContext = createContext<InventoryContextValue | null>(null);

function toInventoryCard(item: PersistedInventory): InventoryCard {
  return {
    ...item,
    projProfit: item.stickerPrice - item.amountPaid,
    stock: 1,
  };
}

function toCompletedSale(sale: PersistedCompletedSale): CompletedSale {
  return { ...sale };
}

function buildInventoryImageUrl(
  imageUrl: string | undefined,
  productId: number | null | undefined,
  catalogBase64?: string
): string | undefined {
  const trimmed = imageUrl?.trim() ?? '';
  // A URL generated by the TCGplayer CDN fallback has this exact prefix and
  // should not be treated as user-supplied custom image data.
  const isGeneratedCdn = trimmed.startsWith(INVENTORY_IMAGE_BASE);

  // 1. inventory.custom_image_data (valid URL or base64/ data URI).
  if (trimmed && !isGeneratedCdn) {
    // iOS / Android block cleartext http://. Always serve remote images over HTTPS.
    if (trimmed.startsWith('http://')) {
      return trimmed.replace(/^http:\/\//, 'https://');
    }
    return trimmed;
  }

  // 2. Offline catalog base64 thumbnail shipped with the downloaded catalog.
  if (catalogBase64) {
    const sanitized = sanitizeImageUrl(catalogBase64);
    if (sanitized) return sanitized;
  }

  // 3. Existing generated CDN URL (keep it so the 404 fallback UI can handle it).
  if (trimmed) {
    return trimmed;
  }

  // 4. Build a new TCGplayer CDN URL from product_id.
  if (productId == null) return undefined;
  const id = Math.trunc(Number(productId));
  if (Number.isNaN(id)) return undefined;
  return `${INVENTORY_IMAGE_BASE}/${id}.jpg`;
}

function buildVariantMap(cards: InventoryCard[]): Record<number, string> {
  const map: Record<number, string> = {};
  for (const card of cards) {
    if (card.productId == null) continue;
    if (map[card.productId] == null) {
      map[card.productId] = card.productType ?? card.rarity ?? 'Normal';
    }
  }
  return map;
}

async function hydrateCatalogPrices(
  cards: InventoryCard[],
  getConditionedMarket: (price: number, condition?: string) => number
): Promise<InventoryCard[]> {
  const productIds = [
    ...new Set(cards.map((c) => c.productId).filter((id): id is number => id != null)),
  ];
  if (productIds.length === 0) return cards;

  try {
    const catalog = await openCatalogDatabase();
    const [data, base64Map] = await Promise.all([
      getProductMarketData(catalog, productIds, buildVariantMap(cards)),
      getCatalogImageBase64(catalog, productIds),
    ]);

    return cards.map((card) => {
      if (card.productId == null) return card;
      const market = data[card.productId];
      const base64 = base64Map[card.productId];

      const updates: Partial<InventoryCard> = {};
      if (market) {
        updates.liveMarket = getConditionedMarket(market.marketPrice, card.condition);
        updates.productType = market.matchedSubType;
      }
      updates.imageUrl = buildInventoryImageUrl(
        card.imageUrl,
        card.productId,
        base64
      );

      if (Object.keys(updates).length === 0) return card;
      return { ...card, ...updates };
    });
  } catch (err) {
    console.error('Failed to hydrate catalog prices:', err);
    return cards;
  }
}

export function InventoryProvider({ children }: { children: ReactNode }) {
  const { userId } = useAuth();
  const { getCashOffer, getStickerPrice, getConditionedMarket } = useVendorSettings();
  const dbRef = useRef<import('expo-sqlite').SQLiteDatabase | null>(null);

  const [inventory, setInventory] = useState<InventoryCard[]>([]);
  const [completedSales, setCompletedSales] = useState<CompletedSale[]>([]);
  const [pendingSyncCount, setPendingSyncCount] = useState(0);
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncFatalError, setSyncFatalError] = useState<string | null>(null);

  const recalculatePendingCount = useCallback(async () => {
    if (!dbRef.current || !userId) return;
    try {
      const count = await getPendingInventoryCount(dbRef.current, userId);
      setPendingSyncCount(count);
    } catch (err) {
      console.error('Failed to recalculate pending sync count:', err);
    }
  }, [userId]);

  const triggerSync = useCallback(async () => {
    if (isSyncing || !dbRef.current || !userId) return;
    setIsSyncing(true);
    setSyncFatalError(null);
    try {
      await pushPendingInventoryChanges(dbRef.current, userId);
      await pullCloudInventory(dbRef.current, userId);
      const [active, completed] = await Promise.all([
        loadActiveInventory(dbRef.current, userId),
        loadCompletedSales(dbRef.current, userId),
      ]);
      await recalculatePendingCount();
      const enriched = await hydrateCatalogPrices(
        active.map(toInventoryCard),
        getConditionedMarket
      );
      setInventory(enriched);
      setCompletedSales(completed.map(toCompletedSale));
    } catch (err) {
      const message =
        err instanceof Error ? err.message : 'Unexpected sync failure';
      console.error('triggerSync failed:', message);
      if (err instanceof SyncFatalError) {
        setSyncFatalError(message);
      }
    } finally {
      setIsSyncing(false);
    }
  }, [isSyncing, userId, recalculatePendingCount, getConditionedMarket]);

  const clearPendingSyncsCallback = useCallback(async () => {
    if (!dbRef.current || !userId) return;
    setIsSyncing(true);
    try {
      await clearPendingSyncs(dbRef.current, userId);
      setSyncFatalError(null);
      await recalculatePendingCount();
    } catch (err) {
      console.error('clearPendingSyncs failed:', err);
    } finally {
      setIsSyncing(false);
    }
  }, [userId, recalculatePendingCount]);

  const forceWipeAndResync = useCallback(async () => {
    if (!dbRef.current || !userId) return;
    setIsSyncing(true);
    setSyncFatalError(null);
    try {
      await dbRef.current.withTransactionAsync(async () => {
        await dbRef.current!.runAsync('DELETE FROM inventory');
        await dbRef.current!.runAsync(
          'UPDATE sync_metadata SET last_updated = 0 WHERE user_id = ?',
          userId
        );
      });
      await triggerSync();
    } catch (err) {
      const message =
        err instanceof Error ? err.message : 'Unexpected wipe/resync failure';
      console.error('forceWipeAndResync failed:', message);
      if (err instanceof SyncFatalError) {
        setSyncFatalError(message);
      }
    } finally {
      setIsSyncing(false);
    }
  }, [userId, triggerSync]);

  // Initialize the SQLite bridge and hydrate the in-memory inventory from the
  // local database. Catalog prices are re-resolved per card so stale or
  // wrong-variant liveMarket values are not locked into the UI.
  useEffect(() => {
    if (!userId) return;

    let mounted = true;

    const hydrate = async () => {
      try {
        const { db: database } = await initializeDatabase();
        if (!mounted) return;
        dbRef.current = database;

        const [active, completed] = await Promise.all([
          loadActiveInventory(database, userId),
          loadCompletedSales(database, userId),
        ]);

        const enriched = await hydrateCatalogPrices(
          active.map(toInventoryCard),
          getConditionedMarket
        );

        if (mounted) {
          setInventory(enriched);
          setCompletedSales(completed.map(toCompletedSale));
        }

        if (mounted) {
          await recalculatePendingCount();
        }
      } catch (err) {
        console.error('Inventory hydration failed:', err);
      }
    };

    hydrate();

    return () => {
      mounted = false;
    };
  }, [userId, recalculatePendingCount, getConditionedMarket]);

  const addInventoryCard = useCallback(
    async (card: InventoryInput) => {
      let liveMarket = card.liveMarket;
      let productType = card.productType;
      let imageUrl = card.imageUrl;

      if (card.productId != null) {
        try {
          const catalog = await openCatalogDatabase();
          const [data, base64Map] = await Promise.all([
            getProductMarketData(catalog, [card.productId], {
              [card.productId]: card.productType ?? card.rarity ?? 'Normal',
            }),
            getCatalogImageBase64(catalog, [card.productId]),
          ]);
          const market = data[card.productId];
          const base64 = base64Map[card.productId];
          if (market) {
            liveMarket = getConditionedMarket(market.marketPrice, card.condition);
            productType = market.matchedSubType;
          }
          imageUrl = buildInventoryImageUrl(imageUrl, card.productId, base64);
        } catch (err) {
          console.error('Catalog price lookup failed:', err);
        }
      }

      const amountPaid =
        typeof card.amountPaid === 'number'
          ? card.amountPaid
          : getCashOffer(liveMarket);
      const rawSticker =
        typeof card.stickerPrice === 'number'
          ? card.stickerPrice
          : getStickerPrice(liveMarket);
      const stickerPrice = getStickerPrice(rawSticker);

      const newCard: InventoryCard = {
        ...card,
        id: generateId(),
        rarity: productType ?? card.rarity,
        productType,
        imageUrl,
        liveMarket,
        amountPaid,
        stickerPrice,
        projProfit: stickerPrice - amountPaid,
        stock: 1,
      };

      setInventory((prev) => [newCard, ...prev]);

      if (dbRef.current && userId) {
        try {
          await upsertInventoryItem(dbRef.current, {
            id: newCard.id,
            userId,
            name: newCard.name,
            number: newCard.number,
            set: newCard.set,
            rarity: newCard.rarity,
            productType: newCard.productType,
            condition: newCard.condition,
            liveMarket: newCard.liveMarket,
            amountPaid: newCard.amountPaid,
            stickerPrice: newCard.stickerPrice,
            isBulk: newCard.isBulk ?? false,
            imageUrl: newCard.imageUrl,
            productId: card.productId ?? null,
          });
          await recalculatePendingCount();
        } catch (err) {
          console.error('addInventoryItem failed:', err);
        }
      }
    },
    [getCashOffer, getStickerPrice, getConditionedMarket, userId, recalculatePendingCount]
  );

  const removeInventoryCard = useCallback(
    async (id: string) => {
      setInventory((prev) => prev.filter((c) => c.id !== id));

      if (dbRef.current && userId) {
        try {
          await softDeleteInventoryItem(dbRef.current, id);
          await recalculatePendingCount();
        } catch (err) {
          console.error('removeInventoryItem failed:', err);
        }
      }
    },
    [userId, recalculatePendingCount]
  );

  const updateInventoryCard = useCallback(
    async (updates: InventoryUpdate) => {
      const existing = inventory.find((c) => c.id === updates.id);
      if (!existing) return;

      const name = updates.name ?? existing.name;
      const number = updates.number ?? existing.number;
      const set = updates.set ?? existing.set;
      const rarity = updates.rarity ?? existing.rarity;
      const condition = updates.condition ?? existing.condition;
      let imageUrl = updates.imageUrl ?? existing.imageUrl;
      const amountPaid =
        typeof updates.amountPaid === 'number'
          ? updates.amountPaid
          : existing.amountPaid;
      const stickerPrice =
        typeof updates.stickerPrice === 'number'
          ? updates.stickerPrice
          : existing.stickerPrice;
      const isBulk = updates.isBulkDeal ?? existing.isBulk;

      let liveMarket = updates.liveMarket ?? existing.liveMarket;
      let productType = updates.productType ?? existing.productType;

      if (existing.productId != null) {
        try {
          const catalog = await openCatalogDatabase();
          const [data, base64Map] = await Promise.all([
            getProductMarketData(catalog, [existing.productId], {
              [existing.productId]:
                updates.productType ?? updates.rarity ?? existing.productType ?? existing.rarity ?? 'Normal',
            }),
            getCatalogImageBase64(catalog, [existing.productId]),
          ]);
          const market = data[existing.productId];
          const base64 = base64Map[existing.productId];
          if (market) {
            liveMarket = getConditionedMarket(market.marketPrice, condition);
            productType = market.matchedSubType;
          }
          imageUrl = buildInventoryImageUrl(imageUrl, existing.productId, base64);
        } catch (err) {
          console.error('Catalog price recompute failed:', err);
        }
      }

      const updated: InventoryCard = {
        ...existing,
        id: updates.id,
        name,
        number,
        set,
        rarity,
        productType,
        condition,
        imageUrl,
        liveMarket,
        amountPaid,
        stickerPrice,
        isBulk,
        projProfit: stickerPrice - amountPaid,
      };

      setInventory((prev) =>
        prev.map((c) => (c.id === updates.id ? updated : c))
      );

      if (dbRef.current && userId) {
        try {
          await upsertInventoryItem(dbRef.current, {
            id: updated.id,
            userId,
            name: updated.name,
            number: updated.number,
            set: updated.set,
            rarity: updated.rarity,
            productType: updated.productType,
            condition: updated.condition,
            liveMarket: updated.liveMarket,
            amountPaid: updated.amountPaid,
            stickerPrice: updated.stickerPrice,
            isBulk: updated.isBulk ?? false,
            imageUrl: updated.imageUrl,
            productId: updates.productId ?? existing.productId,
          });
          await recalculatePendingCount();
        } catch (err) {
          console.error('updateInventoryItem failed:', err);
        }
      }
    },
    [inventory, userId, getConditionedMarket, recalculatePendingCount]
  );

  const sellInventoryCard = useCallback(
    async (id: string, soldPrice?: number) => {
      const card = inventory.find((c) => c.id === id);
      if (!card) return;

      const price = soldPrice ?? card.stickerPrice;
      const sale: CompletedSale = {
        id: card.id,
        name: card.name,
        number: card.number,
        set: card.set,
        condition: card.condition,
        acquiredCost: card.amountPaid,
        soldPrice: price,
        dateSold: new Date().toISOString(),
      };

      setInventory((prev) => prev.filter((c) => c.id !== id));
      setCompletedSales((prev) => [sale, ...prev]);

      if (dbRef.current && userId) {
        try {
          await markInventorySold(dbRef.current, id, price, sale.dateSold);
          await recalculatePendingCount();
        } catch (err) {
          console.error('markInventorySold failed:', err);
        }
      }
    },
    [inventory, userId, recalculatePendingCount]
  );

  const clearInventory = useCallback(() => {
    setInventory([]);
  }, []);

  const undoCompletedSale = useCallback(
    async (sale: CompletedSale) => {
      let persisted: PersistedInventory | null = null;
      if (dbRef.current && userId) {
        try {
          persisted = await getInventoryItem(dbRef.current, sale.id);
          await unmarkInventorySold(dbRef.current, sale.id);
          await recalculatePendingCount();
        } catch (err) {
          console.error('undoCompletedSale failed:', err);
        }
      }

      const stickerPrice =
        persisted?.stickerPrice ?? getStickerPrice(sale.soldPrice);
      const liveMarket = persisted?.liveMarket ?? sale.soldPrice;

      const restored: InventoryCard = {
        id: sale.id,
        name: sale.name,
        number: sale.number,
        set: sale.set,
        condition: sale.condition,
        liveMarket,
        amountPaid: sale.acquiredCost,
        stickerPrice,
        projProfit: stickerPrice - sale.acquiredCost,
        stock: 1,
        isBulk: persisted?.isBulk ?? false,
        imageUrl: persisted?.imageUrl,
      };

      setCompletedSales((prev) => prev.filter((s) => s.id !== sale.id));
      setInventory((prev) => [restored, ...prev]);
    },
    [getStickerPrice, userId, recalculatePendingCount]
  );

  const value = useMemo(
    () => ({
      inventory,
      addInventoryCard,
      removeInventoryCard,
      updateInventoryCard,
      sellInventoryCard,
      clearInventory,
      completedSales,
      undoCompletedSale,
      pendingSyncCount,
      isSyncing,
      syncFatalError,
      triggerSync,
      clearPendingSyncs: clearPendingSyncsCallback,
      forceWipeAndResync,
    }),
    [
      inventory,
      completedSales,
      addInventoryCard,
      removeInventoryCard,
      updateInventoryCard,
      sellInventoryCard,
      clearInventory,
      undoCompletedSale,
      pendingSyncCount,
      isSyncing,
      syncFatalError,
      triggerSync,
      clearPendingSyncsCallback,
      forceWipeAndResync,
    ]
  );

  return (
    <InventoryContext.Provider value={value}>
      {children}
    </InventoryContext.Provider>
  );
}

export function useInventory() {
  const context = useContext(InventoryContext);
  if (!context) {
    throw new Error('useInventory must be used within an InventoryProvider');
  }
  return context;
}
